"""new fields in user model

Revision ID: 19470c947ffe
Revises: bd879d04e043
Create Date: 2026-06-23 15:24:22.158402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19470c947ffe'
down_revision = 'bd879d04e043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
